export const fakeRecipeGroup = {
  results: [
    {
      id: 716429,
      title: "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs",
      readyInMinutes: 45,
      servings: 2,
      sourceUrl:
        "http://fullbellysisters.blogspot.com/2012/06/pasta-with-garlic-scallions-cauliflower.html",
      image: "pasta-with-garlic-scallions-cauliflower-bread-crumbs-716429.jpg",
    },
    {
      id: 715538,
      title: "What to make for dinner tonight?? Bruschetta Style Pork & Pasta",
      readyInMinutes: 35,
      servings: 5,
      sourceUrl: "http://www.pinkwhen.com/make-dinner-tonight/",
      image: "what-to-make-for-dinner-tonight-bruschetta-style-pork-pasta-715538.jpg",
    },
    {
      id: 634873,
      title: "Best Baked Macaroni and Cheese",
      readyInMinutes: 45,
      servings: 12,
      sourceUrl: "http://www.foodista.com/recipe/H3FCFX57/best-baked-macaroni-and-cheese",
      image: "Best-Baked-Macaroni-and-Cheese-634873.jpg",
    },
    {
      id: 660382,
      title: "Smoked Salmon Pasta",
      readyInMinutes: 45,
      servings: 4,
      sourceUrl: "http://www.foodista.com/recipe/YFCWP7PB/smoked-salmon-pasta",
      image: "Smoked-Salmon-Pasta-660382.jpg",
    },
    {
      id: 634629,
      title: "Beef Lo Mein Noodles",
      readyInMinutes: 45,
      servings: 4,
      sourceUrl: "https://www.foodista.com/recipe/8QKG6BC8/beef-lo-mein",
      image: "Beef-Lo-Mein-Noodles-634629.jpg",
    },
    {
      id: 657312,
      title: "Pumpkin gnocchi with basil and Parmesan",
      readyInMinutes: 45,
      servings: 6,
      sourceUrl: "https://www.foodista.com/recipe/VWGPYN7W/pumpkin-gnocchi-with-basil-and-parmesan",
      image: "Pumpkin-gnocchi-with-basil-and-Parmesan-657312.jpg",
    },
    {
      id: 637593,
      title: "Cheese Tortellini With Shrimp In Tomato Cream Sauce",
      readyInMinutes: 45,
      servings: 4,
      sourceUrl:
        "http://www.foodista.com/recipe/ZTD3WYNC/cheese-tortellini-with-shrimp-in-tomato-cream-sauce",
      image: "Cheese-Tortellini-With-Shrimp-In-Tomato-Cream-Sauce-637593.jpg",
    },
    {
      id: 1098350,
      title: "Light Greek Lemon Chicken Orzo Soup",
      readyInMinutes: 30,
      servings: 8,
      sourceUrl: "https://www.foodista.com/recipe/DPVTGWX6/light-greek-lemon-chicken-orzo-soup",
      image: "light-greek-lemon-chicken-orzo-soup-1098350.jpg",
    },
    {
      id: 654835,
      title: "Pasta e Fagioli (Pasta and Beans)",
      readyInMinutes: 45,
      servings: 6,
      sourceUrl: "https://www.foodista.com/recipe/QF3SKD4Y/pasta-e-fagioli-pasta-and-beans",
      image: "Pasta-e-Fagioli-(Pasta-and-Beans)-654835.jpg",
    },
    {
      id: 639629,
      title: "Classic Macaroni and Cheese",
      readyInMinutes: 45,
      servings: 6,
      sourceUrl: "http://www.foodista.com/recipe/RL6K6X3J/classic-macaroni-and-cheese",
      image: "Classic-Macaroni-and-Cheese-639629.jpg",
    },
  ],
  baseUri: "https://spoonacular.com/recipeImages/",
  offset: 0,
  number: 10,
  totalResults: 141,
  processingTimeMs: 63,
  expires: 1673177016882,
  isStale: false,
}
